name: "Checkout"
description: "Checkout limited git history to speed up CI"
inputs:
  checkout-head-only:
    description: "For PRs, checkout only the head SHA without merge commit"
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0
        fetch-tags: ${{ github.event_name != 'release' }}
        ref: ${{ (github.event_name == 'pull_request' && inputs.checkout-head-only == 'true') && github.event.pull_request.head.sha || '' }}
